/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package displayimages;
import java.awt.Container;
import java.awt.EventQueue;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JLabel;
/**
 *
 * @author User
 */
public class DisplayImages extends JFrame {
    /**
     * Creates new form Images_From_Folder_Navigation
     */
    public DisplayImages() throws IOException {
        initComponents();
       // display first image
        showImage(pos,index,nation);
    }
    
// the index of the images
    int pos = 0;
    int index = 0;
    int nation = 0;
    final File srcFolder = new File("E:\\atayi\\main\\dataset\\casia\\casia-temp");
 
    public static List<String> listFilesForFolder(final File folder, List<String> list) {
       boolean firstRead = false;
          for (final File fileEntry : folder.listFiles()) {
              if (fileEntry.isDirectory()) {
                  listFilesForFolder(fileEntry, list);
              } else if(!firstRead){
                  list.add(fileEntry.getAbsolutePath());
                  //System.out.println(fileEntry.getAbsolutePath());
                  firstRead = true;
              }
          }
          return list;
      }
    // get images list
    public List<String>getImages()
    {
      List<String> imageList = new ArrayList<>();
      imageList = listFilesForFolder(srcFolder ,imageList);
      return imageList;
    }

// display the image by index
    public void showImage(int index,int pos, int nation) throws IOException
    {
        List<String> imagesList = getImages();
        
        String nextImage = imagesList.get(pos);
        String imageName = imagesList.get(index);
        
        ImageIcon icon = new ImageIcon(nextImage);
        Image image = icon.getImage();
        jLabel_Image.setIcon(new ImageIcon(image));
        
        
        int lastIndxDot = imageName.lastIndexOf('\\');
        String folderPath = imageName.substring(0, lastIndxDot);
        System.out.println(folderPath);
        
        int lastIndxDot2 = folderPath.lastIndexOf('\\');
        String folderName = folderPath.substring(lastIndxDot2 + 1);
        //System.out.println(folderName);
        
        String Imagefile = imageName.substring(imageName.lastIndexOf("\\")+1);
        System.out.println(Imagefile);
//        int lastIndexUnderLine = Imagefile.lastIndexOf('_');
//        String finalImageName = Imagefile.substring(0, lastIndexUnderLine);
        
        //System.out.println(folderPath);
        File srcFile = new File(folderPath);
        //new File(folderPath).mkdirs();
       
        if (nation == 1){ //EasternPerson
            String fileName = "E:\\atayi\\main\\dataset\\casia\\Eastern\\" + folderName;
            Path path = Paths.get(fileName);
            File file = new File (fileName);
            if (!Files.exists(path)) {
                Files.createDirectory(path);
                //System.out.println("Directory created");
            } else {

                //System.out.println("Directory already exists");
            }
            copyFolder(srcFile, file);
        }
        else if (nation == 2){ //WesternPerson
            String fileName = "E:\\atayi\\main\\dataset\\casia\\Western\\" + folderName;
            Path path = Paths.get(fileName);
            File file = new File (fileName);
            if (!Files.exists(path)) {

                Files.createDirectory(path);
                //System.out.println("Directory created");
            } else {

                //System.out.println("Directory already exists");
            }
            copyFolder(srcFile, file);
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel_Image = new javax.swing.JLabel();
        //jButton1 = new javax.swing.JButton();
        jButton_Next = new javax.swing.JButton();
        jButton_Previous = new javax.swing.JButton();
        //jButton_Last = new javax.swing.JButton();
        
        jLabel_Image.setHorizontalAlignment(JLabel.CENTER);
        
        
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        
        jButton_Next.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_Next.setText("Eastern");
        jButton_Next.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jButton_Next.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_Next.setIconTextGap(0);
        jButton_Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    jButton_EasternActionPerformed(evt);
                } catch (IOException ex) {
                    Logger.getLogger(DisplayImages.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });

        jButton_Previous.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_Previous.setText("Western");
        jButton_Previous.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jButton_Previous.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_Previous.setIconTextGap(0);
        jButton_Previous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    jButton_WesternActionPerformed(evt);
                } catch (IOException ex) {
                    Logger.getLogger(DisplayImages.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });



        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_Image, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jButton_Next)
                .addGap(44, 44, 44)
                .addComponent(jButton_Previous)
                .addGap(49, 49, 49)
                )
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel_Image, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Next, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(jButton_Previous, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    )
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>                        

     // The First , Next , Previous ,Last Navigation Buttons
                                     

     // Next
    private void jButton_EasternActionPerformed(java.awt.event.ActionEvent evt) throws IOException {                                             
       pos = pos + 1;
       nation = 1;
       if(pos >= getImages().size())
       {
           pos  = getImages().size() - 1;
       }
       showImage(pos-1,pos,nation);
    }                                            

     // Previous
    private void jButton_WesternActionPerformed(java.awt.event.ActionEvent evt) throws IOException {                                                 
       pos = pos + 1;
       nation = 2;
       if(pos >= getImages().size())
       {
           pos  = getImages().size() - 1;
       }
       showImage(pos-1 , pos ,nation);
    }                                                
    
    
    
    private static void copyFolder(File sourceFolder, File destinationFolder) throws IOException
    {
        //Check if sourceFolder is a directory or file
        //If sourceFolder is file; then copy the file directly to new location
        if (sourceFolder.isDirectory())
        {
            //Verify if destinationFolder is already present; If not then create it
            if (!destinationFolder.exists())
            {
                destinationFolder.mkdir();
                //System.out.println("Directory created :: " + destinationFolder);
            }
             
            //Get all files from source directory
            String files[] = sourceFolder.list();
             
            //Iterate over all files and copy them to destinationFolder one by one
            for (String file : files)
            {
                File srcFile = new File(sourceFolder, file);
                File destFile = new File(destinationFolder, file);
                 
                //Recursive function call
                copyFolder(srcFile, destFile);
            }
        }
        else
        {
            //Copy the file content from one place to another
            Files.copy(sourceFolder.toPath(), destinationFolder.toPath(), StandardCopyOption.REPLACE_EXISTING);
            //System.out.println("File copied :: " + destinationFolder);
        }
    }
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DisplayImages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DisplayImages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DisplayImages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DisplayImages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new DisplayImages().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(DisplayImages.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    
    
    

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton_Next;
    private javax.swing.JButton jButton_Previous;
    private javax.swing.JLabel jLabel_Image;
    // End of variables declaration    
    
}
